### ISSUE TITLE
proxy examples do not reflect changes

### ISSUE THREAD

**Issue by vollmerr** [sapphi-red/vite-setup-catalogue#15]
Thanks for creating these examples. I am trying to use a reverse proxy based off your examples, however the `with-proxy` and `with-proxy-no-websocket` examples do not reflect updates made to code. It only ever shows the initial code when the container was built.

Setting "DEBUG" to "connect:dispatcher" logs when hitting the browser, but nothing when code is changed. The hmr is not working, and refreshing the browser after code is changed still shows the old code aswell. Currently the only way to use those examples is to rebuild the container after every code update.

It works in the tests for me, and when I add the pollingConfig functionality to the vite configs. Is that the recommended approach to use polling?

Steps to reproduce:
- open `with-proxy` example
- run `yarn install`
- run `docker compose -p with-proxy-dev-nginx -f compose.dev-nginx.yaml up`
- open `http://localhost:3030/`
- in `main.js` change `<h1>Hello Vite!</h1>` to `<h1>Hello Vite!!!</h1>`
- hmr not triggered, refreshing page does not reflect changes

OS Name	Microsoft Windows 11 Pro
Docker version 20.10.7, build f0df350

**Comment by sapphi-red** [comment]
I guess you are facing this one.
https://vitejs.dev/config/server-options.html#server-watch:~:text=Using%20Vite%20on%20Windows%20Subsystem%20for%20Linux%20(WSL)%202

**Comment by vollmerr** [comment]
Ah, yes that looks like that would be the issue. Thanks!
